#!/bin/sh
echo "Downloading latest installer"
rm ./oba-install
curl -LOk https://raw.github.com/bbodenmiller/onebusaway-iphone-test-releases/master/oba-install
chmod +x ./oba-install

if [[ $# -ge 1 ]];
then
  ./oba-install $@
else
  ./oba-install
fi