#!/bin/sh
function checklastcommanderrorexit {
  RC=$?
  #echo "exit code: $RC"
  if [[ $RC -ne "0" ]]; then
    echo "An error occured: $RC, no changes have been made"
    exit -1
  fi
}

#check if branch specified, else set to develop
if [[ $# -lt 1 ]];
then
  BRANCH="develop"
else
  BRANCH=$1
fi

echo "Verifying branch/installation file exists..." 1>&2
FILE_REPONSE_CODE=0
FILE_REPONSE_CODE="`curl -sLkI -w "%{http_code}" https://github.com/bbodenmiller/onebusaway-iphone-test-releases/raw/$BRANCH/OneBusAway.ipa -o /dev/null`"
if [ $FILE_REPONSE_CODE -ne 200 ]; then
  echo "Installation file/branch ($BRANCH, $FILE_REPONSE_CODE) does not exist, no changes have been made"
  exit -1
fi

mkdir -p Downloads
cd Downloads

if [[ -f OneBusAway.ipa ]]; then
  echo "Cleaning old installation files..." 1>&2
  rm -f OneBusAway.ipa
fi

echo "Downloading app..."
curl -LOk https://github.com/bbodenmiller/onebusaway-iphone-test-releases/raw/$BRANCH/OneBusAway.ipa

echo "Validating downloaded app..." 1>&2
checklastcommanderrorexit
if [[ ! -f OneBusAway.ipa ]]; then
  echo "File did not download properly, no changes have been made"
  exit -1
fi

echo "Installing app..."
installipa -f OneBusAway.ipa